package main

import (
	"embed"
	"fmt"
	"os"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"

	"delta-tool/app"
)

//go:embed all:frontend/dist
var frontendAssets embed.FS

// Note: This file is generated by running: go run . generate-cache
//
//go:embed data/weapon_codes.json
var defaultCacheData []byte

func main() {
	// Check for command line flags
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "generate-cache":
			// Development mode: generate cache from Excel
			fmt.Println("========================================")
			fmt.Println("  Excel to JSON Cache Converter")
			fmt.Println("  Development Tool Only")
			fmt.Println("========================================")
			fmt.Println()

			application := app.NewAppWithExcel()

			fmt.Println("Loading weapon codes from Excel files...")
			codes, err := application.LoadWeaponCodes()
			if err != nil {
				fmt.Printf("Error loading weapon codes: %v\n", err)
				os.Exit(1)
			}

			fmt.Printf("Successfully loaded %d weapon codes\n", len(codes))
			fmt.Println()

			fmt.Println("Saving to cache file...")
			cacheManager := app.NewCacheManager()
			if err := cacheManager.Save(codes, "local-excel"); err != nil {
				fmt.Printf("Error saving cache: %v\n", err)
				os.Exit(1)
			}

			fmt.Println()
			fmt.Println("========================================")
			fmt.Println("  Conversion Complete!")
			fmt.Println("========================================")
			fmt.Printf("Cache file: %s\n", cacheManager.GetCachePath())
			fmt.Printf("Total codes: %d\n", len(codes))
			fmt.Printf("Version: %s\n", app.CacheVersion)
			fmt.Println()
			fmt.Println("You can now build the application without")
			fmt.Println("including the Excel files.")
			fmt.Println("========================================")
			return

		default:
			fmt.Printf("Unknown command: %s\n", os.Args[1])
			fmt.Println("Usage:")
			fmt.Println("  delta-tool              # Run the GUI application")
			fmt.Println("  delta-tool generate-cache  # Generate cache from Excel files (dev only)")
			os.Exit(1)
		}
	}

	// Create an instance of the app structure
	application := app.NewApp()

	// Initialize cache from embedded data if needed
	cacheManager := app.NewCacheManager()
	if err := cacheManager.InitializeFromEmbedded(defaultCacheData); err != nil {
		fmt.Printf("Warning: Failed to initialize cache: %v\n", err)
	}

	// Create application with options
	err := wails.Run(&options.App{
		Title:  "delta-tool-app",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: frontendAssets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        application.Startup,
		Bind: []interface{}{
			application,
		},
	})

	if err != nil {
		println("Error:", err.Error())
	}
}
