// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetCacheInfo():Promise<Record<string, any>>;

export function GetWeaponCodes():Promise<Array<app.WeaponCode>>;

export function GetWeaponCodesFromDaoZai():Promise<Array<app.WeaponCode>>;

export function GetWeaponCodesFromWeaponMaster():Promise<Array<app.WeaponCode>>;

export function Greet(arg1:string):Promise<string>;

export function LoadWeaponCodes():Promise<Array<app.WeaponCode>>;

export function LoadWeaponCodesFromDaoZai():Promise<Array<app.WeaponCode>>;

export function LoadWeaponCodesFromWeaponMaster():Promise<Array<app.WeaponCode>>;
