// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCacheInfo() {
  return window['go']['app']['App']['GetCacheInfo']();
}

export function GetWeaponCodes() {
  return window['go']['app']['App']['GetWeaponCodes']();
}

export function GetWeaponCodesFromDaoZai() {
  return window['go']['app']['App']['GetWeaponCodesFromDaoZai']();
}

export function GetWeaponCodesFromWeaponMaster() {
  return window['go']['app']['App']['GetWeaponCodesFromWeaponMaster']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function LoadWeaponCodes() {
  return window['go']['app']['App']['LoadWeaponCodes']();
}

export function LoadWeaponCodesFromDaoZai() {
  return window['go']['app']['App']['LoadWeaponCodesFromDaoZai']();
}

export function LoadWeaponCodesFromWeaponMaster() {
  return window['go']['app']['App']['LoadWeaponCodesFromWeaponMaster']();
}
